Fix?

diff --git a/.github/workflows/manifest.yml b/.github/workflows/manifest.yml
--- a/.github/workflows/manifest.yml
+++ b/.github/workflows/manifest.yml
@@ -33,8 +33,16 @@ jobs:
           git config user.name "MissouriMRDT"
           git config user.email "marsrover@mst.edu"
 
+      - name: Rebase Changes
+        run: |
+          git fetch origin ${{ github.head_ref }}
+          git rebase origin/${{ github.head_ref }}
+
       - name: Commit Manifest
         run: |
           git add -f src/RoveComm/RoveCommManifest.h
           git commit -m "** Automated - Manifest Update **" || echo "No changes to commit"
-          git push origin HEAD:${{ github.head_ref }} || echo "Failed to push changes"
+
+      - name: Push Changes
+        run: |
+          git push origin HEAD:${{ github.head_ref }} --force-with-lease || echo "Failed to push changes"
