Fix?

diff --git a/.github/workflows/manifest.yml b/.github/workflows/manifest.yml
--- a/.github/workflows/manifest.yml
+++ b/.github/workflows/manifest.yml
@@ -32,10 +32,9 @@ jobs:
         run: |
           git config user.name "MissouriMRDT"
           git config user.email "marsrover@mst.edu"
-          echo ${{ github.head_ref }}
 
       - name: Commit Manifest
         run: |
           git add -f src/RoveComm/RoveCommManifest.h
-          git commit -m "** Automated - Manifest Update **"
-          git push origin ${{ github.head_ref }}
+          git commit -m "** Automated - Manifest Update **" || echo "No changes to commit"
+          git push origin HEAD:${{ github.head_ref }} || echo "Failed to push changes"
